// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7He7-TbEr2-vhVJPsPXXMguY5fi-QOBI',
    appId: '1:637411239582:android:06b210b78f8ba4d3b6fd8f',
    messagingSenderId: '637411239582',
    projectId: 'invoicemanager-909f5',
    databaseURL: 'https://invoicemanager-909f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'invoicemanager-909f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAchVTG8I-WNuababvbKFAMpYGDeTthuk',
    appId: '1:637411239582:ios:eb86d7d5e0d0f650b6fd8f',
    messagingSenderId: '637411239582',
    projectId: 'invoicemanager-909f5',
    databaseURL: 'https://invoicemanager-909f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'invoicemanager-909f5.appspot.com',
    androidClientId: '637411239582-6gv945p4mtt96essf25674s2t6mtek4o.apps.googleusercontent.com',
    iosClientId: '637411239582-aioiom7lopopohjmk1r1ejcfl9bk49vu.apps.googleusercontent.com',
    iosBundleId: 'com.querosys.invoicegenerator',
  );
}
